### ISSUE TITLE
amazing work!

### ISSUE THREAD

**Issue by xpeng** [zhaw/neural_style#1]
nice work, it looks these models can create so crazy images! are these pkl models generated or pretrained by some method in mxnet? if i can generate my own style, how could i? thanks!

**Comment by zhaw** [comment]
Those models were trained by myself, with different methods. I'm still looking for better training method and the training part of code is very messy and hard to use by now. When I find some universal way to train those models, I'll organize the training code and put it here.
The basic idea of training those models is described in this [paper](http://120.52.73.75/arxiv.org/pdf/1603.03417v1.pdf). But as you can see, the result is more like averaging the texture and the content, instead of 'style transfer'. I tried a lot other stuff to get better result and I'm still exploring.

glad you like it, have fun!

**Comment by xpeng** [comment]
thanks, i'll try this soon.
