### ISSUE TITLE
Will you please explain the params

### ISSUE THREAD

**Issue by wlxyhy** [zhaw/neural_style#5]
Will you please explain the parameters, such as
 --content-weight ,why it can be an array, not just a number;
--style-size, why you use this, isn't '--size'enough?
--num-res, --num-rotation, num-scale, --patch-size and so on

**Comment by zhaw** [comment]
The basic idea of this method is to reconstruct the feature map(relu3_1 for example) of the content image using patches extracted from the feature map from the style image and '--patch-size' specifies how big those patches are. When using CNN to extract features, the scale of the input image matters. We want the output image has the same style with the style image at every different scale, so I build an image pyramid(see symbol.py for detail) and '--num-res' specifies how many levels the pyramid has. The VGG network will extract features on each level so we have num_res feature maps. We need to specify content weight and style weight for every feature map so '--content-weight' is an array which has num_res number, as well as '--style-weight'.
'--size' specifies the size of the content and output image. Size of the style image doesn't has to be the same. Same image with different size will give very different style.
Since we are reconstructing with patches, the more different patches we have, the better the output will be. So we augment the style image by rotating and rescaling it and '--num-rotation' and '--num-scale' specifies how many time the transformation should be done.
For more details, please read the paper. The basic idea is same.

**Comment by wlxyhy** [comment]
Thank you for your detail explaination
